#!/usr/bin/env python3
"""Small dependency-free controller for technology-research runs."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "skill" / "technology-research" / "templates"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", value)
    return value.strip("-") or "research-run"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def cmd_doctor(_: argparse.Namespace) -> int:
    print(f"root: {ROOT}")
    print(f"python: {sys.executable}")
    for command in ("pandoc", "git"):
        print(f"{command}: {shutil.which(command) or 'not found'}")
    print("status: ready for skill-driven research")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    config = Path(args.config).resolve()
    if not config.is_file():
        raise SystemExit(f"config not found: {config}")
    slug = args.slug or slugify(config.stem)
    run_dir = Path(args.out or ROOT / "runs" / slug).resolve()
    if run_dir.exists() and any(run_dir.iterdir()) and not args.force:
        raise SystemExit(f"run directory is not empty; use --force only when intended: {run_dir}")
    run_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config, run_dir / "request.yaml")
    shutil.copy2(TEMPLATE_DIR / "report.md", run_dir / "REPORT.md")
    (run_dir / "sources.jsonl").write_text("", encoding="utf-8")
    (run_dir / "claims.jsonl").write_text("", encoding="utf-8")
    (run_dir / "evidence").mkdir(exist_ok=True)
    (run_dir / "validation").mkdir(exist_ok=True)
    (run_dir / "plan.md").write_text(
        "# Research plan\n\nGenerated by researchctl. The Agent should replace this with a report-oriented question tree.\n",
        encoding="utf-8",
    )
    manifest = {
        "created_at": utc_now(),
        "run_dir": str(run_dir),
        "status": "initialized",
        "workflow_version": "0.1.0",
    }
    (run_dir / "run-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir)
    return 0


REQUIRED_HEADINGS = [
    "摘要与关键判断",
    "核心机制与概念边界",
    "技术路线和关键差异",
    "工程应用、产品化和部署条件",
    "争议、负面证据和未解决问题",
    "结论与行动建议",
]


def cmd_verify(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    report = run_dir / "REPORT.md"
    errors = []
    if not report.is_file():
        errors.append("REPORT.md is missing")
    else:
        text = report.read_text(encoding="utf-8")
        for heading in REQUIRED_HEADINGS:
            if f"## {heading}" not in text:
                errors.append(f"missing heading: {heading}")
        if "{{" in text:
            errors.append("report still contains template placeholders")
    for name in ("request.yaml", "sources.jsonl", "claims.jsonl"):
        if not (run_dir / name).is_file():
            errors.append(f"missing artifact: {name}")
    result = {"checked_at": utc_now(), "status": "fail" if errors else "pass", "errors": errors}
    (run_dir / "validation" / "structure.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 1 if errors else 0


def markdown_to_html(markdown: str, title: str) -> str:
    lines = []
    for raw in markdown.splitlines():
        line = raw.rstrip()
        if line.startswith("# "):
            lines.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("> "):
            lines.append(f"<blockquote>{line[2:]}</blockquote>")
        elif not line:
            lines.append("")
        else:
            lines.append(f"<p>{line}</p>")
    body = "\n".join(lines)
    return (
        "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
        f"<title>{title}</title><style>body{{max-width:900px;margin:40px auto;"
        "padding:0 24px;font-family:system-ui,'Microsoft YaHei',sans-serif;"
        "line-height:1.8;color:#202124}h1,h2,h3{line-height:1.3}"
        "blockquote{border-left:4px solid #bbb;padding-left:1em;color:#555}"
        f"</style></head><body>{body}</body></html>"
    )


def cmd_render(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    report = run_dir / "REPORT.md"
    if not report.is_file():
        raise SystemExit(f"missing: {report}")
    text = report.read_text(encoding="utf-8")
    title = next(
        (line[2:].strip() for line in text.splitlines() if line.startswith("# ")),
        "Technology Research Report",
    )
    (run_dir / "REPORT.html").write_text(markdown_to_html(text, title), encoding="utf-8")
    pandoc = shutil.which("pandoc")
    if pandoc:
        result = subprocess.run([pandoc, str(report), "-o", str(run_dir / "REPORT.pdf")], check=False)
        if result.returncode == 0 and (run_dir / "REPORT.pdf").is_file():
            print("pdf: generated by pandoc")
        else:
            print("pdf: skipped (pandoc PDF engine is unavailable)")
    else:
        print("pdf: skipped (pandoc not found)")
    print(f"html: {run_dir / 'REPORT.html'}")
    return 0


def cmd_package(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    files = []
    for path in sorted(run_dir.rglob("*")):
        if path.is_file() and path.name != "package-manifest.json":
            files.append(
                {
                    "path": str(path.relative_to(run_dir)),
                    "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "bytes": path.stat().st_size,
                }
            )
    manifest = {"packaged_at": utc_now(), "run_dir": str(run_dir), "files": files}
    (run_dir / "package-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir / "package-manifest.json")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="researchctl")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor").set_defaults(func=cmd_doctor)
    init = sub.add_parser("init")
    init.add_argument("--config", default="request.yaml")
    init.add_argument("--slug")
    init.add_argument("--out")
    init.add_argument("--force", action="store_true")
    init.set_defaults(func=cmd_init)
    for name, func in (("verify", cmd_verify), ("render", cmd_render), ("package", cmd_package)):
        command = sub.add_parser(name)
        command.add_argument("--run", required=True)
        command.set_defaults(func=func)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())

