#!/usr/bin/env python3
"""Small dependency-free controller for technology-research runs."""

from __future__ import annotations

import argparse
import base64
import hashlib
import html
import json
import mimetypes
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "skill" / "technology-research" / "templates"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", value)
    return value.strip("-") or "research-run"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def cmd_doctor(_: argparse.Namespace) -> int:
    print(f"root: {ROOT}")
    print(f"python: {sys.executable}")
    for command in ("pandoc", "git"):
        print(f"{command}: {shutil.which(command) or 'not found'}")
    print("status: ready for skill-driven research")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    config = Path(args.config).resolve()
    if not config.is_file():
        raise SystemExit(f"config not found: {config}")
    slug = args.slug or slugify(config.stem)
    run_dir = Path(args.out or ROOT / "runs" / slug).resolve()
    if run_dir.exists() and any(run_dir.iterdir()) and not args.force:
        raise SystemExit(f"run directory is not empty; use --force only when intended: {run_dir}")
    run_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config, run_dir / "request.yaml")
    shutil.copy2(TEMPLATE_DIR / "report.md", run_dir / "REPORT.md")
    (run_dir / "sources.jsonl").write_text("", encoding="utf-8")
    (run_dir / "claims.jsonl").write_text("", encoding="utf-8")
    (run_dir / "evidence").mkdir(exist_ok=True)
    (run_dir / "validation").mkdir(exist_ok=True)
    (run_dir / "plan.md").write_text(
        "# Research plan\n\nGenerated by researchctl. The Agent should replace this with a report-oriented question tree.\n",
        encoding="utf-8",
    )
    manifest = {
        "created_at": utc_now(),
        "run_dir": str(run_dir),
        "status": "initialized",
        "workflow_version": "0.2.0",
    }
    (run_dir / "run-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir)
    return 0


REQUIRED_SECTION_GROUPS = [
    ("摘要", ("摘要与核心判断", "摘要与关键判断")),
    ("机制", ("技术问题与作用机制", "核心机制与概念边界")),
    ("路线", ("技术路线与关键差异", "技术路线和关键差异")),
    ("证据与边界", ("实验证据、性能与适用边界", "实验结果与性能边界")),
    ("工程与应用", ("工程化、产业格局与应用选择", "工程应用、产品化和部署条件")),
    ("结论", ("结论与未来路线", "结论与行动建议")),
]
ALLOWED_VERIFICATION_LEVELS = {
    "metadata_verified",
    "abstract_verified",
    "full_text_verified",
    "official_text_verified",
    "secondary_only",
    "unavailable",
    "conflict",
}
SECONDARY_HOSTS = {
    "eurekalert.org",
    "go.gale.com",
    "news.qq.com",
    "ouci.dntb.gov.ua",
    "scite.ai",
    "semanticscholar.org",
    "www.163.com",
    "www.ebiaozhun.com",
    "www.guifanku.com",
}
OFFICIAL_CLAIM_TYPES = {"regulatory_driver", "standards_status", "regulation", "standard"}
STRONG_LANGUAGE = re.compile(r"(?:目前)?唯一|任何量产|完全不存在|量产前装为零|已经证明")
INTERNAL_ID = re.compile(r"\b(?:S|E|C)-[A-Z0-9-]+\b")


def _read_jsonl(path: Path, label: str, errors: list[str]) -> list[dict]:
    if not path.is_file():
        errors.append(f"missing artifact: {path.name}")
        return []
    records = []
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        try:
            value = json.loads(raw)
        except json.JSONDecodeError as exc:
            errors.append(f"{label} line {line_number}: invalid JSON ({exc.msg})")
            continue
        if not isinstance(value, dict):
            errors.append(f"{label} line {line_number}: record must be an object")
            continue
        records.append(value)
    return records


def _yaml_list(text: str, key: str) -> set[str]:
    lines = text.splitlines()
    values: set[str] = set()
    for index, raw in enumerate(lines):
        match = re.match(rf"^(\s*){re.escape(key)}\s*:\s*(.*)$", raw)
        if not match:
            continue
        indent = len(match.group(1))
        inline = match.group(2).strip()
        if inline.startswith("[") and inline.endswith("]"):
            values.update(item.strip().strip("'\"").lower() for item in inline[1:-1].split(",") if item.strip())
            continue
        for following in lines[index + 1 :]:
            if not following.strip():
                continue
            following_indent = len(following) - len(following.lstrip())
            if following_indent <= indent:
                break
            item = re.match(r"^\s*-\s*(.+?)\s*$", following)
            if item:
                values.add(item.group(1).strip().strip("'\"").lower())
    return values


def _yaml_bool(text: str, key: str, default: bool = False) -> bool:
    match = re.search(rf"^\s*{re.escape(key)}\s*:\s*(true|false)\s*$", text, re.MULTILINE | re.IGNORECASE)
    return default if not match else match.group(1).lower() == "true"


def _host(url: str) -> str:
    return (urlsplit(url).hostname or "").lower()


def _verify_sources(records: list[dict], exclusions: set[str], errors: list[str], warnings: list[str]) -> dict[str, dict]:
    source_by_id: dict[str, dict] = {}
    title_by_url: dict[str, str] = {}
    patents_excluded = "patents" in exclusions or "patent" in exclusions
    for index, source in enumerate(records, start=1):
        prefix = f"source {index}"
        source_id = str(source.get("source_id", "")).strip()
        source_class = str(source.get("source_class", "")).strip().lower()
        legacy_source_class = str(source.get("source_type", "")).strip().lower()
        title = str(source.get("title", "")).strip()
        url = str(source.get("canonical_url", "")).strip()
        authority = str(source.get("authority", "")).strip().lower()
        level = str(source.get("verification_level", "")).strip().lower()
        if not source_id:
            errors.append(f"{prefix}: missing source_id")
        elif source_id in source_by_id:
            errors.append(f"{prefix}: duplicate source_id {source_id}")
        else:
            source_by_id[source_id] = source
        if not source_class:
            errors.append(f"{prefix}: missing source_class (legacy source_type is not release-safe)")
        if not title:
            errors.append(f"{prefix}: missing title")
        if not url:
            errors.append(f"{prefix}: missing canonical_url")
        if authority not in {"primary", "official", "secondary"}:
            errors.append(f"{prefix}: authority must be primary, official, or secondary")
        if level not in ALLOWED_VERIFICATION_LEVELS:
            errors.append(f"{prefix}: invalid verification_level {level or '<missing>'}")
        if authority == "primary" and _host(url) in SECONDARY_HOSTS:
            errors.append(f"{prefix}: secondary or aggregator URL marked primary: {url}")
        if level in {"full_text_verified", "official_text_verified"}:
            if not str(source.get("locator", "")).strip():
                errors.append(f"{prefix}: {level} requires locator")
            if not str(source.get("extracted_evidence", "")).strip():
                errors.append(f"{prefix}: {level} requires extracted_evidence")
            if not str(source.get("content_hash", "")).strip():
                errors.append(f"{prefix}: {level} requires content_hash")
        if not str(source.get("accessed_at", "")).strip():
            errors.append(f"{prefix}: missing accessed_at")
        if patents_excluded and ("patent" in source_class or "patent" in legacy_source_class or "专利" in title.lower()):
            errors.append(f"{prefix}: excluded patent material is present")
        if url:
            normalized_url = url.rstrip("/").lower()
            normalized_title = re.sub(r"\W+", " ", title.lower()).strip()
            previous = title_by_url.get(normalized_url)
            if previous and previous != normalized_title:
                errors.append(f"{prefix}: canonical URL is assigned to conflicting titles")
            title_by_url[normalized_url] = normalized_title
        if level in {"metadata_verified", "abstract_verified", "secondary_only"}:
            warnings.append(f"{prefix}: evidence level is limited ({level})")
    return source_by_id


def _verify_claims(
    records: list[dict],
    source_by_id: dict[str, dict],
    exclusions: set[str],
    require_counter: bool,
    errors: list[str],
    warnings: list[str],
) -> None:
    claim_ids: set[str] = set()
    patents_excluded = "patents" in exclusions or "patent" in exclusions
    for index, claim in enumerate(records, start=1):
        prefix = f"claim {index}"
        claim_id = str(claim.get("claim_id", "")).strip()
        text = str(claim.get("claim", "")).strip()
        importance = str(claim.get("importance", "")).strip().lower()
        support_type = str(claim.get("support_type", "")).strip().lower()
        claim_type = str(claim.get("claim_type", "")).strip().lower()
        evidence_ids = claim.get("evidence_ids", [])
        counter_ids = claim.get("counter_evidence_ids", [])
        counter_note = str(claim.get("counter_evidence_note", "")).strip()
        if not claim_id:
            errors.append(f"{prefix}: missing claim_id")
        elif claim_id in claim_ids:
            errors.append(f"{prefix}: duplicate claim_id {claim_id}")
        claim_ids.add(claim_id)
        if not text:
            errors.append(f"{prefix}: missing claim text")
        if importance not in {"decision_critical", "supporting"}:
            errors.append(f"{prefix}: importance must be decision_critical or supporting")
        if support_type not in {"direct", "indirect", "mixed"}:
            errors.append(f"{prefix}: invalid support_type")
        if not isinstance(evidence_ids, list) or not evidence_ids:
            errors.append(f"{prefix}: evidence_ids must be a non-empty list")
            evidence_ids = []
        missing = [source_id for source_id in evidence_ids if source_id not in source_by_id]
        if missing:
            errors.append(f"{prefix}: unknown evidence_ids {missing}")
        if importance == "decision_critical":
            levels = {
                str(source_by_id[source_id].get("verification_level", ""))
                for source_id in evidence_ids
                if source_id in source_by_id
            }
            if not levels.intersection({"full_text_verified", "official_text_verified"}):
                errors.append(f"{prefix}: decision-critical claim lacks full-text or official evidence")
            if support_type == "indirect":
                errors.append(f"{prefix}: decision-critical claim cannot rely only on indirect support")
            if not claim.get("conditions"):
                errors.append(f"{prefix}: decision-critical claim lacks conditions")
        if require_counter and importance == "decision_critical" and not counter_ids and not counter_note:
            errors.append(f"{prefix}: decision-critical claim lacks counter-evidence or a counter-evidence note")
        if counter_ids and not isinstance(counter_ids, list):
            errors.append(f"{prefix}: counter_evidence_ids must be a list")
            counter_ids = []
        unknown_counter = [source_id for source_id in counter_ids if source_id not in source_by_id]
        if unknown_counter:
            errors.append(f"{prefix}: unknown counter_evidence_ids {unknown_counter}")
        if patents_excluded and ("patent" in claim_type or "专利" in text.lower()):
            errors.append(f"{prefix}: excluded patent material is used in a claim")
        if claim_type in OFFICIAL_CLAIM_TYPES or re.search(r"\b(?:GB|IEC|ISO)\s*[/T-]?\s*\d", text, re.IGNORECASE):
            levels = {
                str(source_by_id[source_id].get("verification_level", ""))
                for source_id in evidence_ids
                if source_id in source_by_id
            }
            if "official_text_verified" not in levels:
                errors.append(f"{prefix}: standards or regulatory claim lacks official_text_verified evidence")
        if not str(claim.get("scope_limit", "")).strip():
            warnings.append(f"{prefix}: scope_limit is empty")
        if str(claim.get("confidence", "")).strip().lower() not in {"low", "medium", "high"}:
            errors.append(f"{prefix}: confidence must be low, medium, or high")


def _verify_report(report: Path, source_count: int, errors: list[str], warnings: list[str]) -> None:
    if not report.is_file():
        errors.append("REPORT.md is missing")
        return
    text = report.read_text(encoding="utf-8")
    if "{{" in text:
        errors.append("report still contains template placeholders")
    for label, alternatives in REQUIRED_SECTION_GROUPS:
        if not any(f"## {heading}" in text for heading in alternatives):
            errors.append(f"missing reader section: {label}")
    if "## 参考文献" not in text:
        errors.append("missing reader-facing references section")
    reader_text = text.split("## 参考文献", 1)[0]
    leaked_ids = sorted(set(INTERNAL_ID.findall(reader_text)))
    if leaked_ids:
        errors.append(f"internal evidence IDs leaked into reader narrative: {leaked_ids[:5]}")
    citation_count = len(LINK_RE.findall(text))
    minimum_citations = min(3, source_count)
    if source_count and citation_count < minimum_citations:
        errors.append(
            f"report has {source_count} sources but only {citation_count} descriptive Markdown citations; "
            f"at least {minimum_citations} are required"
        )
    for paragraph in re.split(r"\n\s*\n", reader_text):
        if STRONG_LANGUAGE.search(paragraph) and not LINK_RE.search(paragraph):
            errors.append("unsupported exclusivity or certainty language in reader narrative")
            break
    audit_headings = ("## 证据附录", "## 检索日志", "## 论断与证据映射")
    for heading in audit_headings:
        if heading in text:
            errors.append(f"backstage audit section appears in reader report: {heading[3:]}")
    if len(text) < 1500:
        warnings.append("report is unusually short for a professional technology survey")


def _verify_review(run_dir: Path, errors: list[str]) -> str:
    review_path = run_dir / "validation" / "report-review.json"
    if not review_path.is_file():
        errors.append("missing independent review: validation/report-review.json")
        return "needs_review"
    try:
        review = json.loads(review_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        errors.append(f"invalid report-review.json: {exc}")
        return "needs_review"
    if review.get("independent") is not True:
        errors.append("report review is not marked independent")
    findings = review.get("findings", [])
    if not isinstance(findings, list):
        errors.append("review findings must be a list")
        findings = []
    open_major = [item for item in findings if isinstance(item, dict) and item.get("severity") in {"blocker", "major"}]
    if review.get("status") != "pass" or open_major:
        errors.append("independent review has unresolved blocker or major findings")
    recommendation = str(review.get("release_recommendation", "needs_review"))
    if recommendation not in {"ready", "ready_with_limitations"}:
        errors.append("review does not recommend release")
        return "needs_review"
    return recommendation


def cmd_verify(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    errors: list[str] = []
    warnings: list[str] = []
    request = run_dir / "request.yaml"
    if not request.is_file():
        errors.append("missing artifact: request.yaml")
        request_text = ""
    else:
        request_text = request.read_text(encoding="utf-8")
    exclusions = _yaml_list(request_text, "exclude")
    require_counter = _yaml_bool(request_text, "require_counter_evidence", default=True)
    sources = _read_jsonl(run_dir / "sources.jsonl", "sources", errors)
    claims = _read_jsonl(run_dir / "claims.jsonl", "claims", errors)
    source_by_id = _verify_sources(sources, exclusions, errors, warnings)
    _verify_claims(claims, source_by_id, exclusions, require_counter, errors, warnings)

    release_state = "needs_review"
    if args.stage == "release":
        _verify_report(run_dir / "REPORT.md", len(sources), errors, warnings)
        release_state = _verify_review(run_dir, errors)
    result = {
        "checked_at": utc_now(),
        "stage": args.stage,
        "status": "fail" if errors else "pass",
        "release_state": release_state if not errors and args.stage == "release" else "needs_review",
        "source_count": len(sources),
        "claim_count": len(claims),
        "errors": errors,
        "warnings": warnings,
    }
    if not args.no_write:
        validation_dir = run_dir / "validation"
        validation_dir.mkdir(exist_ok=True)
        (validation_dir / "quality.json").write_text(
            json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 1 if errors else 0


IMAGE_RE = re.compile(
    r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"([^\"]*)\")?\)"
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)(?:\s+\"([^\"]*)\")?\)")
CODE_RE = re.compile(r"`([^`\n]+)`")
RAW_URL_RE = re.compile(r"https?://[^\s<>()\[\]\"'，。！？；：、]+")
IMAGE_MIME_TYPES = {
    ".avif": "image/avif",
    ".bmp": "image/bmp",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
}


def _safe_path(path: str, run_dir: Path) -> Path | None:
    """Resolve a local asset without allowing it to escape the run directory."""
    parsed = urlsplit(path)
    if parsed.scheme or parsed.netloc:
        return None
    candidate = (run_dir / unquote(parsed.path)).resolve()
    try:
        candidate.relative_to(run_dir.resolve())
    except ValueError:
        return None
    return candidate


def _embedded_image(path: str, run_dir: Path, issues: list[str]) -> str:
    """Return a data URI for a local image, or a safe fallback for external assets."""
    if path.startswith("data:"):
        return path
    parsed = urlsplit(path)
    if parsed.scheme in {"http", "https"} or parsed.netloc:
        issues.append(f"external image is not self-contained: {path}")
        return path

    asset = _safe_path(path, run_dir)
    if asset is None or not asset.is_file():
        issues.append(f"missing or unsafe image asset: {path}")
        return ""
    mime = mimetypes.guess_type(asset.name)[0] or IMAGE_MIME_TYPES.get(asset.suffix.lower())
    if not mime or not mime.startswith("image/"):
        issues.append(f"unsupported image type: {path}")
        return ""
    encoded = base64.b64encode(asset.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def _format_plain_inline(text: str) -> str:
    """Escape text and render emphasis that is outside links, images, and code."""
    escaped = html.escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def inline_to_html(text: str, run_dir: Path, issues: list[str]) -> str:
    """Render the small Markdown inline subset needed by research reports."""
    tokens = []
    for match in IMAGE_RE.finditer(text):
        tokens.append((match.start(), match.end(), "image", match))
    for match in LINK_RE.finditer(text):
        if not any(start <= match.start() < end for start, end, _, _ in tokens):
            tokens.append((match.start(), match.end(), "link", match))
    for match in CODE_RE.finditer(text):
        if not any(start <= match.start() < end for start, end, _, _ in tokens):
            tokens.append((match.start(), match.end(), "code", match))
    for match in RAW_URL_RE.finditer(text):
        if not any(start <= match.start() < end for start, end, _, _ in tokens):
            tokens.append((match.start(), match.end(), "url", match))
    tokens.sort(key=lambda item: item[0])

    output = []
    cursor = 0
    for start, end, kind, match in tokens:
        output.append(_format_plain_inline(text[cursor:start]))
        if kind == "code":
            output.append(f"<code>{html.escape(match.group(1))}</code>")
            cursor = end
            continue
        if kind == "url":
            target = match.group(0)
            escaped_target = html.escape(target, quote=True)
            output.append(f'<a href="{escaped_target}">{html.escape(target)}</a>')
            cursor = end
            continue
        label, target, title = match.group(1), match.group(2), match.group(3)
        if kind == "image":
            src = _embedded_image(target, run_dir, issues)
            if src:
                caption = html.escape(label) if label else ""
                title_attr = f' title="{html.escape(title)}"' if title else ""
                output.append(
                    f'<figure><img src="{html.escape(src, quote=True)}" '
                    f'alt="{caption}"{title_attr}>'
                    f"{f'<figcaption>{caption}</figcaption>' if caption else ''}</figure>"
                )
            else:
                output.append(f'<span class="missing-asset">[缺少图片：{html.escape(label)}]</span>')
        else:
            title_attr = f' title="{html.escape(title)}"' if title else ""
            output.append(
                f'<a href="{html.escape(target, quote=True)}"{title_attr}>'
                f"{_format_plain_inline(label)}</a>"
            )
        cursor = end
    output.append(_format_plain_inline(text[cursor:]))
    return "".join(output)


def _table_cells(line: str) -> list[str]:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|") and not line.endswith("\\|"):
        line = line[:-1]
    return [cell.strip().replace("\\|", "|") for cell in line.split("|")]


def _is_table_separator(line: str) -> bool:
    cells = _table_cells(line)
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell) for cell in cells)


def _render_table(header: str, separator: str, rows: list[str], run_dir: Path, issues: list[str]) -> str:
    header_cells = _table_cells(header)
    body_rows = [_table_cells(row) for row in rows]
    aligns = []
    for cell in _table_cells(separator):
        aligns.append("center" if cell.startswith(":") and cell.endswith(":") else "left" if cell.startswith(":") or not cell.endswith(":") else "right")

    def render_cell(cell: str, index: int) -> str:
        align = aligns[index] if index < len(aligns) else "left"
        return f'<td style="text-align:{align}">{inline_to_html(cell, run_dir, issues)}</td>'

    head = "".join(
        f'<th style="text-align:{aligns[index] if index < len(aligns) else "left"}">{inline_to_html(cell, run_dir, issues)}</th>'
        for index, cell in enumerate(header_cells)
    )
    body = "".join(
        "<tr>" + "".join(render_cell(cell, index) for index, cell in enumerate(row)) + "</tr>"
        for row in body_rows
    )
    return f'<div class="table-wrap"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def markdown_to_html(markdown: str, title: str, run_dir: Path) -> tuple[str, list[str]]:
    """Render report Markdown into a self-contained, offline-readable HTML file."""
    lines = markdown.splitlines()
    rendered = []
    issues: list[str] = []
    index = 0
    paragraph: list[str] = []
    list_items: list[str] = []
    list_kind: str | None = None
    heading_ids: dict[int, str] = {}
    heading_counts: dict[str, int] = {}
    toc_items: list[tuple[str, str]] = []
    for line_index, line in enumerate(lines):
        heading = re.match(r"^(#{1,6})\s+(.+)$", line.rstrip())
        if not heading:
            continue
        level = len(heading.group(1))
        heading_text = re.sub(r"[*_`]", "", heading.group(2)).strip()
        base = slugify(heading_text)
        heading_counts[base] = heading_counts.get(base, 0) + 1
        heading_id = base if heading_counts[base] == 1 else f"{base}-{heading_counts[base]}"
        heading_ids[line_index] = heading_id
        if level == 2 and heading_text != "参考文献":
            toc_items.append((heading_id, heading_text))

    def flush_paragraph() -> None:
        if paragraph:
            text = " ".join(paragraph)
            if len(paragraph) == 1 and IMAGE_RE.fullmatch(text.strip()):
                rendered.append(inline_to_html(text, run_dir, issues))
            else:
                rendered.append(f'<p>{inline_to_html(text, run_dir, issues)}</p>')
            paragraph.clear()

    def flush_list() -> None:
        nonlocal list_kind
        if list_items:
            tag = list_kind or "ul"
            rendered.append(f"<{tag}>" + "".join(f"<li>{item}</li>" for item in list_items) + f"</{tag}>")
            list_items.clear()
        list_kind = None

    while index < len(lines):
        raw = lines[index].rstrip()
        if raw.startswith("```"):
            flush_paragraph()
            flush_list()
            language = html.escape(raw[3:].strip())
            index += 1
            code_lines = []
            while index < len(lines) and not lines[index].startswith("```"):
                code_lines.append(lines[index])
                index += 1
            if index < len(lines):
                index += 1
            class_attr = f' class="language-{language}"' if language else ""
            rendered.append(f"<pre><code{class_attr}>{html.escape(chr(10).join(code_lines))}</code></pre>")
            continue
        if index + 1 < len(lines) and "|" in raw and _is_table_separator(lines[index + 1]):
            flush_paragraph()
            flush_list()
            table_rows = []
            index += 2
            while index < len(lines) and lines[index].strip() and "|" in lines[index]:
                table_rows.append(lines[index].rstrip())
                index += 1
            rendered.append(_render_table(raw, lines[index - len(table_rows) - 1], table_rows, run_dir, issues))
            continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", raw)
        if heading:
            flush_paragraph()
            flush_list()
            level = len(heading.group(1))
            heading_id = heading_ids.get(index, slugify(heading.group(2)))
            rendered.append(
                f'<h{level} id="{html.escape(heading_id, quote=True)}">'
                f"{inline_to_html(heading.group(2), run_dir, issues)}</h{level}>"
            )
            index += 1
            continue
        if raw.startswith("> "):
            flush_paragraph()
            flush_list()
            rendered.append(f"<blockquote>{inline_to_html(raw[2:], run_dir, issues)}</blockquote>")
            index += 1
            continue
        list_match = re.match(r"^\s*([-*+] |\d+\. )(.+)$", raw)
        if list_match:
            flush_paragraph()
            kind = "ol" if list_match.group(1)[0].isdigit() else "ul"
            if list_kind and list_kind != kind:
                flush_list()
            list_kind = kind
            list_items.append(inline_to_html(list_match.group(2), run_dir, issues))
            index += 1
            continue
        if not raw.strip():
            flush_paragraph()
            flush_list()
            index += 1
            continue
        if re.fullmatch(r"\s*([-*_])(?:\s*\1){2,}\s*", raw):
            flush_paragraph()
            flush_list()
            rendered.append("<hr>")
            index += 1
            continue
        paragraph.append(raw.strip())
        index += 1
    flush_paragraph()
    flush_list()

    if toc_items:
        toc = (
            '<nav class="toc" aria-label="目录"><div class="toc-title">目录</div><ol>'
            + "".join(
                f'<li><a href="#{html.escape(heading_id, quote=True)}">{html.escape(label)}</a></li>'
                for heading_id, label in toc_items
            )
            + "</ol></nav>"
        )
        insert_at = next((position + 1 for position, item in enumerate(rendered) if item.startswith("<h1")), 0)
        rendered.insert(insert_at, toc)

    body = "\n".join(rendered)
    document = (
        "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{html.escape(title)}</title><style>"
        "*{box-sizing:border-box}body{max-width:1000px;margin:40px auto;padding:0 24px;"
        "font-family:system-ui,'Microsoft YaHei',sans-serif;line-height:1.8;color:#202124;"
        "background:#fff}h1,h2,h3,h4,h5,h6{line-height:1.3;margin-top:1.6em}"
        "p{margin:0 0 1em}blockquote{border-left:4px solid #bbb;padding-left:1em;color:#555;"
        "margin-left:0}ul,ol{padding-left:2em}.table-wrap{overflow-x:auto;margin:1.2em 0}"
        "table{border-collapse:collapse;width:100%;min-width:560px;font-size:.95em}"
        "th,td{border:1px solid #d7dbe0;padding:.55em .7em;vertical-align:top}"
        "th{background:#f3f5f7;font-weight:650}tr:nth-child(even){background:#fafbfc}"
        "figure{margin:1.2em 0;text-align:center}figure img{max-width:100%;height:auto;"
        "display:inline-block}figcaption{color:#5f6368;font-size:.9em;margin-top:.35em}"
        "pre{overflow:auto;padding:1em;background:#f6f8fa;border-radius:6px}"
        "code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}"
        ".toc{margin:1.5em 0 2.5em;padding:1em 1.25em;background:#f7f9fb;border-radius:8px}"
        ".toc-title{font-weight:700;margin-bottom:.45em}.toc ol{margin:.2em 0;padding-left:1.5em}"
        ".missing-asset{color:#b3261e;background:#fce8e6;padding:.1em .3em}"
        "a{color:#1565c0}hr{border:0;border-top:1px solid #d7dbe0;margin:2em 0}"
        "@media print{body{margin:0;max-width:none}a{color:inherit;text-decoration:none}"
        ".table-wrap{overflow:visible}table{min-width:0;font-size:9pt}}"
        f"</style></head><body>{body}</body></html>"
    )
    return document, issues


def cmd_render(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    report = run_dir / "REPORT.md"
    if not report.is_file():
        raise SystemExit(f"missing: {report}")
    text = report.read_text(encoding="utf-8")
    title = next(
        (line[2:].strip() for line in text.splitlines() if line.startswith("# ")),
        "Technology Research Report",
    )
    document, issues = markdown_to_html(text, title, run_dir)
    (run_dir / "REPORT.html").write_text(document, encoding="utf-8")
    for issue in issues:
        print(f"asset: {issue}")
    pandoc = shutil.which("pandoc")
    if pandoc:
        result = subprocess.run([pandoc, str(report), "-o", str(run_dir / "REPORT.pdf")], check=False)
        if result.returncode == 0 and (run_dir / "REPORT.pdf").is_file():
            print("pdf: generated by pandoc")
        else:
            print("pdf: skipped (pandoc PDF engine is unavailable)")
    else:
        print("pdf: skipped (pandoc not found)")
    print(f"html: {run_dir / 'REPORT.html'}")
    return 1 if issues else 0


def cmd_package(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    archive = run_dir / "REPORT-package.zip"
    files = []
    for path in sorted(run_dir.rglob("*")):
        if path.is_file() and path.name not in {"package-manifest.json", archive.name}:
            files.append(
                {
                    "path": str(path.relative_to(run_dir)),
                    "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "bytes": path.stat().st_size,
                }
            )
    manifest = {"packaged_at": utc_now(), "run_dir": str(run_dir), "files": files}
    (run_dir / "package-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir / "package-manifest.json")
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for item in files:
            source = run_dir / item["path"]
            bundle.write(source, item["path"])
        bundle.write(run_dir / "package-manifest.json", "package-manifest.json")
    print(f"archive: {archive}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="researchctl")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor").set_defaults(func=cmd_doctor)
    init = sub.add_parser("init")
    init.add_argument("--config", default="request.yaml")
    init.add_argument("--slug")
    init.add_argument("--out")
    init.add_argument("--force", action="store_true")
    init.set_defaults(func=cmd_init)
    verify = sub.add_parser("verify")
    verify.add_argument("--run", required=True)
    verify.add_argument("--stage", choices=("evidence", "release"), default="release")
    verify.add_argument("--no-write", action="store_true")
    verify.set_defaults(func=cmd_verify)
    for name, func in (("render", cmd_render), ("package", cmd_package)):
        command = sub.add_parser(name)
        command.add_argument("--run", required=True)
        command.set_defaults(func=func)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
