#!/usr/bin/env python3
"""Small dependency-free controller for technology-research runs."""

from __future__ import annotations

import argparse
import base64
import hashlib
import html
import json
import mimetypes
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "skill" / "technology-research" / "templates"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", value)
    return value.strip("-") or "research-run"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def cmd_doctor(_: argparse.Namespace) -> int:
    print(f"root: {ROOT}")
    print(f"python: {sys.executable}")
    for command in ("pandoc", "git"):
        print(f"{command}: {shutil.which(command) or 'not found'}")
    print("status: ready for skill-driven research")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    config = Path(args.config).resolve()
    if not config.is_file():
        raise SystemExit(f"config not found: {config}")
    slug = args.slug or slugify(config.stem)
    run_dir = Path(args.out or ROOT / "runs" / slug).resolve()
    if run_dir.exists() and any(run_dir.iterdir()) and not args.force:
        raise SystemExit(f"run directory is not empty; use --force only when intended: {run_dir}")
    run_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config, run_dir / "request.yaml")
    shutil.copy2(TEMPLATE_DIR / "report.md", run_dir / "REPORT.md")
    (run_dir / "sources.jsonl").write_text("", encoding="utf-8")
    (run_dir / "claims.jsonl").write_text("", encoding="utf-8")
    (run_dir / "evidence").mkdir(exist_ok=True)
    (run_dir / "validation").mkdir(exist_ok=True)
    (run_dir / "plan.md").write_text(
        "# Research plan\n\nGenerated by researchctl. The Agent should replace this with a report-oriented question tree.\n",
        encoding="utf-8",
    )
    manifest = {
        "created_at": utc_now(),
        "run_dir": str(run_dir),
        "status": "initialized",
        "workflow_version": "0.1.0",
    }
    (run_dir / "run-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir)
    return 0


REQUIRED_HEADINGS = [
    "摘要与关键判断",
    "核心机制与概念边界",
    "技术路线和关键差异",
    "工程应用、产品化和部署条件",
    "争议、负面证据和未解决问题",
    "结论与行动建议",
]


def cmd_verify(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    report = run_dir / "REPORT.md"
    errors = []
    if not report.is_file():
        errors.append("REPORT.md is missing")
    else:
        text = report.read_text(encoding="utf-8")
        for heading in REQUIRED_HEADINGS:
            if f"## {heading}" not in text:
                errors.append(f"missing heading: {heading}")
        if "{{" in text:
            errors.append("report still contains template placeholders")
    for name in ("request.yaml", "sources.jsonl", "claims.jsonl"):
        if not (run_dir / name).is_file():
            errors.append(f"missing artifact: {name}")
    result = {"checked_at": utc_now(), "status": "fail" if errors else "pass", "errors": errors}
    (run_dir / "validation" / "structure.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 1 if errors else 0


IMAGE_RE = re.compile(
    r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"([^\"]*)\")?\)"
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)(?:\s+\"([^\"]*)\")?\)")
IMAGE_MIME_TYPES = {
    ".avif": "image/avif",
    ".bmp": "image/bmp",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
}


def _safe_path(path: str, run_dir: Path) -> Path | None:
    """Resolve a local asset without allowing it to escape the run directory."""
    parsed = urlsplit(path)
    if parsed.scheme or parsed.netloc:
        return None
    candidate = (run_dir / unquote(parsed.path)).resolve()
    try:
        candidate.relative_to(run_dir.resolve())
    except ValueError:
        return None
    return candidate


def _embedded_image(path: str, run_dir: Path, issues: list[str]) -> str:
    """Return a data URI for a local image, or a safe fallback for external assets."""
    if path.startswith("data:"):
        return path
    parsed = urlsplit(path)
    if parsed.scheme in {"http", "https"} or parsed.netloc:
        issues.append(f"external image is not self-contained: {path}")
        return path

    asset = _safe_path(path, run_dir)
    if asset is None or not asset.is_file():
        issues.append(f"missing or unsafe image asset: {path}")
        return ""
    mime = mimetypes.guess_type(asset.name)[0] or IMAGE_MIME_TYPES.get(asset.suffix.lower())
    if not mime or not mime.startswith("image/"):
        issues.append(f"unsupported image type: {path}")
        return ""
    encoded = base64.b64encode(asset.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def inline_to_html(text: str, run_dir: Path, issues: list[str]) -> str:
    """Render the small Markdown inline subset needed by research reports."""
    tokens = []
    for match in IMAGE_RE.finditer(text):
        tokens.append((match.start(), match.end(), "image", match))
    for match in LINK_RE.finditer(text):
        if not any(start <= match.start() < end for start, end, _, _ in tokens):
            tokens.append((match.start(), match.end(), "link", match))
    tokens.sort(key=lambda item: item[0])

    output = []
    cursor = 0
    for start, end, kind, match in tokens:
        output.append(html.escape(text[cursor:start]))
        label, target, title = match.group(1), match.group(2), match.group(3)
        if kind == "image":
            src = _embedded_image(target, run_dir, issues)
            if src:
                caption = html.escape(label) if label else ""
                title_attr = f' title="{html.escape(title)}"' if title else ""
                output.append(
                    f'<figure><img src="{html.escape(src, quote=True)}" '
                    f'alt="{caption}"{title_attr}>'
                    f"{f'<figcaption>{caption}</figcaption>' if caption else ''}</figure>"
                )
            else:
                output.append(f'<span class="missing-asset">[缺少图片：{html.escape(label)}]</span>')
        else:
            title_attr = f' title="{html.escape(title)}"' if title else ""
            output.append(
                f'<a href="{html.escape(target, quote=True)}"{title_attr}>'
                f"{html.escape(label)}</a>"
            )
        cursor = end
    output.append(html.escape(text[cursor:]))
    return "".join(output)


def _table_cells(line: str) -> list[str]:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|") and not line.endswith("\\|"):
        line = line[:-1]
    return [cell.strip().replace("\\|", "|") for cell in line.split("|")]


def _is_table_separator(line: str) -> bool:
    cells = _table_cells(line)
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell) for cell in cells)


def _render_table(header: str, separator: str, rows: list[str], run_dir: Path, issues: list[str]) -> str:
    header_cells = _table_cells(header)
    body_rows = [_table_cells(row) for row in rows]
    aligns = []
    for cell in _table_cells(separator):
        aligns.append("center" if cell.startswith(":") and cell.endswith(":") else "left" if cell.startswith(":") or not cell.endswith(":") else "right")

    def render_cell(cell: str, index: int) -> str:
        align = aligns[index] if index < len(aligns) else "left"
        return f'<td style="text-align:{align}">{inline_to_html(cell, run_dir, issues)}</td>'

    head = "".join(
        f'<th style="text-align:{aligns[index] if index < len(aligns) else "left"}">{inline_to_html(cell, run_dir, issues)}</th>'
        for index, cell in enumerate(header_cells)
    )
    body = "".join(
        "<tr>" + "".join(render_cell(cell, index) for index, cell in enumerate(row)) + "</tr>"
        for row in body_rows
    )
    return f'<div class="table-wrap"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def markdown_to_html(markdown: str, title: str, run_dir: Path) -> tuple[str, list[str]]:
    """Render report Markdown into a self-contained, offline-readable HTML file."""
    lines = markdown.splitlines()
    rendered = []
    issues: list[str] = []
    index = 0
    paragraph: list[str] = []
    list_items: list[str] = []
    list_kind: str | None = None

    def flush_paragraph() -> None:
        if paragraph:
            text = " ".join(paragraph)
            if len(paragraph) == 1 and IMAGE_RE.fullmatch(text.strip()):
                rendered.append(inline_to_html(text, run_dir, issues))
            else:
                rendered.append(f'<p>{inline_to_html(text, run_dir, issues)}</p>')
            paragraph.clear()

    def flush_list() -> None:
        nonlocal list_kind
        if list_items:
            tag = list_kind or "ul"
            rendered.append(f"<{tag}>" + "".join(f"<li>{item}</li>" for item in list_items) + f"</{tag}>")
            list_items.clear()
        list_kind = None

    while index < len(lines):
        raw = lines[index].rstrip()
        if raw.startswith("```"):
            flush_paragraph()
            flush_list()
            language = html.escape(raw[3:].strip())
            index += 1
            code_lines = []
            while index < len(lines) and not lines[index].startswith("```"):
                code_lines.append(lines[index])
                index += 1
            if index < len(lines):
                index += 1
            class_attr = f' class="language-{language}"' if language else ""
            rendered.append(f"<pre><code{class_attr}>{html.escape(chr(10).join(code_lines))}</code></pre>")
            continue
        if index + 1 < len(lines) and "|" in raw and _is_table_separator(lines[index + 1]):
            flush_paragraph()
            flush_list()
            table_rows = []
            index += 2
            while index < len(lines) and lines[index].strip() and "|" in lines[index]:
                table_rows.append(lines[index].rstrip())
                index += 1
            rendered.append(_render_table(raw, lines[index - len(table_rows) - 1], table_rows, run_dir, issues))
            continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", raw)
        if heading:
            flush_paragraph()
            flush_list()
            level = len(heading.group(1))
            rendered.append(f"<h{level}>{inline_to_html(heading.group(2), run_dir, issues)}</h{level}>")
            index += 1
            continue
        if raw.startswith("> "):
            flush_paragraph()
            flush_list()
            rendered.append(f"<blockquote>{inline_to_html(raw[2:], run_dir, issues)}</blockquote>")
            index += 1
            continue
        list_match = re.match(r"^\s*([-*+] |\d+\. )(.+)$", raw)
        if list_match:
            flush_paragraph()
            kind = "ol" if list_match.group(1)[0].isdigit() else "ul"
            if list_kind and list_kind != kind:
                flush_list()
            list_kind = kind
            list_items.append(inline_to_html(list_match.group(2), run_dir, issues))
            index += 1
            continue
        if not raw.strip():
            flush_paragraph()
            flush_list()
            index += 1
            continue
        if re.fullmatch(r"\s*([-*_])(?:\s*\1){2,}\s*", raw):
            flush_paragraph()
            flush_list()
            rendered.append("<hr>")
            index += 1
            continue
        paragraph.append(raw.strip())
        index += 1
    flush_paragraph()
    flush_list()

    body = "\n".join(rendered)
    document = (
        "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{html.escape(title)}</title><style>"
        "*{box-sizing:border-box}body{max-width:1000px;margin:40px auto;padding:0 24px;"
        "font-family:system-ui,'Microsoft YaHei',sans-serif;line-height:1.8;color:#202124;"
        "background:#fff}h1,h2,h3,h4,h5,h6{line-height:1.3;margin-top:1.6em}"
        "p{margin:0 0 1em}blockquote{border-left:4px solid #bbb;padding-left:1em;color:#555;"
        "margin-left:0}ul,ol{padding-left:2em}.table-wrap{overflow-x:auto;margin:1.2em 0}"
        "table{border-collapse:collapse;width:100%;min-width:560px;font-size:.95em}"
        "th,td{border:1px solid #d7dbe0;padding:.55em .7em;vertical-align:top}"
        "th{background:#f3f5f7;font-weight:650}tr:nth-child(even){background:#fafbfc}"
        "figure{margin:1.2em 0;text-align:center}figure img{max-width:100%;height:auto;"
        "display:inline-block}figcaption{color:#5f6368;font-size:.9em;margin-top:.35em}"
        "pre{overflow:auto;padding:1em;background:#f6f8fa;border-radius:6px}"
        "code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}"
        ".missing-asset{color:#b3261e;background:#fce8e6;padding:.1em .3em}"
        "a{color:#1565c0}hr{border:0;border-top:1px solid #d7dbe0;margin:2em 0}"
        "@media print{body{margin:0;max-width:none}a{color:inherit;text-decoration:none}"
        ".table-wrap{overflow:visible}table{min-width:0;font-size:9pt}}"
        f"</style></head><body>{body}</body></html>"
    )
    return document, issues


def cmd_render(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    report = run_dir / "REPORT.md"
    if not report.is_file():
        raise SystemExit(f"missing: {report}")
    text = report.read_text(encoding="utf-8")
    title = next(
        (line[2:].strip() for line in text.splitlines() if line.startswith("# ")),
        "Technology Research Report",
    )
    document, issues = markdown_to_html(text, title, run_dir)
    (run_dir / "REPORT.html").write_text(document, encoding="utf-8")
    for issue in issues:
        print(f"asset: {issue}")
    pandoc = shutil.which("pandoc")
    if pandoc:
        result = subprocess.run([pandoc, str(report), "-o", str(run_dir / "REPORT.pdf")], check=False)
        if result.returncode == 0 and (run_dir / "REPORT.pdf").is_file():
            print("pdf: generated by pandoc")
        else:
            print("pdf: skipped (pandoc PDF engine is unavailable)")
    else:
        print("pdf: skipped (pandoc not found)")
    print(f"html: {run_dir / 'REPORT.html'}")
    return 1 if issues else 0


def cmd_package(args: argparse.Namespace) -> int:
    run_dir = Path(args.run).resolve()
    archive = run_dir / "REPORT-package.zip"
    files = []
    for path in sorted(run_dir.rglob("*")):
        if path.is_file() and path.name not in {"package-manifest.json", archive.name}:
            files.append(
                {
                    "path": str(path.relative_to(run_dir)),
                    "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "bytes": path.stat().st_size,
                }
            )
    manifest = {"packaged_at": utc_now(), "run_dir": str(run_dir), "files": files}
    (run_dir / "package-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(run_dir / "package-manifest.json")
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for item in files:
            source = run_dir / item["path"]
            bundle.write(source, item["path"])
        bundle.write(run_dir / "package-manifest.json", "package-manifest.json")
    print(f"archive: {archive}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="researchctl")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor").set_defaults(func=cmd_doctor)
    init = sub.add_parser("init")
    init.add_argument("--config", default="request.yaml")
    init.add_argument("--slug")
    init.add_argument("--out")
    init.add_argument("--force", action="store_true")
    init.set_defaults(func=cmd_init)
    for name, func in (("verify", cmd_verify), ("render", cmd_render), ("package", cmd_package)):
        command = sub.add_parser(name)
        command.add_argument("--run", required=True)
        command.set_defaults(func=func)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())

